### ISSUE TITLE
small issue

### ISSUE THREAD

**Issue by mousa388** [prof18/RSS-Parser#10]
Hi , First thanks for the great library .

i am trying to fetch an rss from this url : https://www.skynewsarabia.com/web/rss/markets.xml

or this : http://gulf.argaam.com/rss/home/sectionid/0?entityId=3

but the application crashes and give me this error : 

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.alrabei.myproject, PID: 6136
                  java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
                      at com.alrabei.myproject.ArticleAdapter.onBindViewHolder(ArticleAdapter.java:100)
                      at com.alrabei.myproject.ArticleAdapter.onBindViewHolder(ArticleAdapter.java:44)`

i am wondering if i can fetch the rss from any website and how

**Comment by prof18** [comment]
Oh, that's because the feed you selected hasn't any categories. I have fixed the issue!
