### ISSUE TITLE
XML too big for SQLite

### ISSUE THREAD

**Issue by skeie** [prof18/RSS-Parser#105]
**Describe the bug**

Seems like I found big RSS feed, bc its too big for SQLite it looks when caching is enabled, any idea on how to solve this without turning of the cache? It would be great if the library could handle it itself, if cache fails, it will try to parse the RSS feed instead of failing.

But you have more context than I have, what do you think?

```

E/SQLiteQuery: exception: Row too big to fit into CursorWindow requiredPos=0, totalRows=1; query: SELECT * FROM feeds 
            WHERE url_hash = ?
            AND charset = ?

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
```

**The link of the RSS Feed**
https://mindpump.libsyn.com/rss

**Comment by prof18** [comment]
Indeed, the caching should be done at "best effort" and the exception should be handled internally. I will look into this!

**Comment by skeie** [comment]
Amazing, thank you!
