### ISSUE TITLE
Support additional RSS feeds from The Verge and Slashdot

### ISSUE THREAD

**Issue by j-roskopf** [prof18/RSS-Parser#113]
Currently, Atom feeds aren't supported. I see there is currently an open PR (https://github.com/prof18/RSS-Parser/pull/94) to add basic support. I've pulled this project down and included it in my personal project and applied the logic within that PR and it still leaves some of the functionality with these 2 feeds missing (http://rss.slashdot.org/Slashdot/slashdotMainatom) (https://www.theverge.com/rss/index.xml). I've added support to completely parse these 2 feeds on my local copy. Are you amenable to me opening a PR to add this support?

**Comment by prof18** [comment]
Thanks for reaching out! I'm planning to merge #94 soon and then you're more than welcome if you want to upstream your changes! 🙏

**Comment by j-roskopf** [comment]
sounds good! :)

**Comment by prof18** [comment]
Hello!
I've merged #94 and  #114 with the initial support; feel free to upstream your changes! 🙏
