### ISSUE TITLE
Get enclosing channel properties from an article

### ISSUE THREAD

**Issue by mayank12gt** [prof18/RSS-Parser#120]
There is no way of getting channel properties like channel name directly from an article. To do so, I have to create a list of pair of article and channel and pass it to my Recycler View adapter which makes it a bit complicated. It would be better if I could just get channel properties from article directly. For Ex-  article.channel.[ANY_CHANNEL_PROPERTY]

**Comment by prof18** [comment]
Hi, 
Having the channel properties inside the article is an app-specific requirement, and it won't supported by the library.
