### ISSUE TITLE
Error (dont know which one) when trying to use the articlelist

### ISSUE THREAD

**Issue by LordFluffy** [prof18/RSS-Parser#14]
So basically, whenever I try to actually use the artcile list, II get an error and nothing loads. But when I put some Toast or Log in the on finish it works.

**Comment by prof18** [comment]
I guess there are some failure with the UI thread. I'm gonna investigate

**Comment by prof18** [comment]
I've checked out. In the onFinish you have to set the result to the view. I can't reproduce your error
