### ISSUE TITLE
is latest release 6.05 or 6.06

### ISSUE THREAD

**Issue by saldous** [prof18/RSS-Parser#144]
the info seems mixed up..
<img width="956" alt="image" src="https://github.com/prof18/RSS-Parser/assets/3334306/6fa7c847-9d99-47bf-8cc7-2e856318cfd1">

**Comment by prof18** [comment]
Uh, sorry about that! I wrote 6.0.6 on the release title 🤦‍♂️

The latest release is 6.0.5.
