### ISSUE TITLE
Please check if the XML is valid

### ISSUE THREAD

**Issue by ngapp-dev** [prof18/RSS-Parser#159]
**Describe the bug**
The bug happens if rss feed has some spaces before tags. It thows exception from AndroidXmlParser:
```
throw RssParsingException(
                message = "Something went wrong during the parsing of the feed. Please check if the XML is valid",
                cause = exception
            )
```
Like an example [https://metan.by/news/rss/](https://metan.by/news/rss/)
If artificially create a feed with missing indents in front, everything works.

**The link of the RSS Feed**
RSS feed caused bug is [https://metan.by/news/rss/](https://metan.by/news/rss/)

**Comment by prof18** [comment]
The issue has been fixed with https://github.com/prof18/RSS-Parser/pull/172

I will release a new version soon
