### ISSUE TITLE
Can you also add support to parse enclosure tag ? Some rss has images as enclosure url attribute.

### ISSUE THREAD

**Issue by PrajeetShrestha** [prof18/RSS-Parser#17]

**Comment by prof18** [comment]
Can you provide an example of the tag?

**Comment by prof18** [comment]
The parser is already getting images from that tag: https://github.com/prof18/RSS-Parser/blob/master/rssparser/src/main/java/com/prof/rssparser/XMLParser.java#L87
Please update to the latest version!

**Comment by PrajeetShrestha** [comment]
You are parsing from key thumbnail, not enclosure. Some rss doesn't have thumbnail but has images and other medias in enclosure tag.
for example this: https://movieweb.com/rss/movie-reviews/
