### ISSUE TITLE
"FATAL EXCEPTION: main" Crash when open URL

### ISSUE THREAD

**Issue by piyush921** [prof18/RSS-Parser#179]
**Describe the bug**
My Andorid Project in kotlin. 
App is crashing on opening this below URL

Logcat:
FATAL EXCEPTION: main
Process: com.shalommediaonline.shalomtv, PID: 15583

**The link of the RSS Feed**
https://rss.app/feeds/wma7VmXqPsxVMb8q.xml

**Comment by prof18** [comment]
I've tried with the URL provided and the parser is working correctly. 

In particular, the parser is returning 404 because the website returns 404
<img width="677" alt="Screenshot 2024-10-06 at 23 37 24" src="https://github.com/user-attachments/assets/27d4fee5-51f8-4ca9-bed7-f7d6ec996230">
