### ISSUE TITLE
Images and structure of content field are not preserved

### ISSUE THREAD

**Issue by mayank12gt** [prof18/RSS-Parser#197]
**Describe the bug**
In some RSS feeds, the "<content:encoded>" field has HTML with defined structure(for ex with p tags for paragraphs) and images, but the content attribute of the RSSItem removes the images and structure, and returns all text as single paragraph. Is there any way to keep the original structure and images or extract the raw html from <content:encoded> so it can be parsed accordingly,

**The link of the RSS Feed**
https://inc42.com/features/feed

The "<content:encoded>" field in this feed has images and paragraphs but on parsing only text is returned in a single paragraph

I just found out, the library is working correctly, i was using an html parser which was the cause of the problem. My apologies

**Comment by prof18** [comment]
@mayank12gt I'm closing the issue based on the last line.
