### ISSUE TITLE
java.text.ParseException: Unparseable date: "Wed, 02 Jan 2019 07:03:36 GMT	" (at offset 0)

### ISSUE THREAD

**Issue by harsmeet** [prof18/RSS-Parser#23]
java.util.concurrent.ExecutionException: java.text.ParseException: Unparseable date: "
	   Wed, 02 Jan 2019 07:03:36 GMT	" (at offset 0)

Please Help

**Comment by prof18** [comment]
oh, I think that there is a problem on the internal parsing of the date. I use this format: Sat, 15 Dec 2018 12:00:32 +0000 but the format specified in the RSS definition is this: Sun, 19 May 2002 15:21:36 GMT. I gonna fix the issue as soon as possible. 

Can you give me the URL of the RSS that you are using so I can make some tests?

**Comment by prof18** [comment]
I've just fixed the issue: https://github.com/prof18/RSS-Parser/commit/10d153cf8c693f87b5fd162717a308ab30fd627e

An update will be available soon

**Comment by harsmeet** [comment]
ok Thanks, 
URL of the RSS :  https://timesofindia.indiatimes.com/rssfeeds/-2128833038.cms

**Comment by prof18** [comment]
I confirm you that now it works also with your feed!

**Comment by harsmeet** [comment]
i also update my code  as mentions in your  new commit.   getDefaultLocale to Englisg only.

**Comment by prof18** [comment]
I tried with your feed and the phone set to English, Italian and Hindi language and always works
