### ISSUE TITLE
Last update blocking UI thread on full Java project

### ISSUE THREAD

**Issue by eagskunst** [prof18/RSS-Parser#24]
I have experience a UI block in my project when upgrading the library from 1.4.4 to 2.0.1. The layout stops responding until all articles are parsed. The parser would make the call [here](https://github.com/eagskunst/GamingNews/blob/develop/app/src/main/java/com/eagskunst/emmanuel/gamingnews/fragments/news_list/mvp/NewsListModel.java) to be represented in [this layout](https://github.com/eagskunst/GamingNews/blob/develop/app/src/main/java/com/eagskunst/emmanuel/gamingnews/fragments/news_list/NewsListFragment.java).

I also tried parsing only one url with the same code and the UI stills blocks.

**Comment by prof18** [comment]
Hi, you can execute the parsing with a background thread, as I did in the sample application: https://github.com/prof18/RSS-Parser/blob/master/samplejava/src/main/java/com/prof/rssparser/sample/java/MainViewModel.java#L60

However, for a better usage I'm releasing right now an update that performs the parsing on an backround thread, so you don't have to change your code.

**Comment by prof18** [comment]
Release 2.0.2 is out: a5f41a3981afc6b6ac4711d1cbea8e3fc4afec15
Please update and let me know if there are troubles!

**Comment by varadmondkar** [comment]
Hey, I have updated version to `2.0.2` and now it is not blocking my UI thread.

Only thing I have to do is, Any UI update which I want to do under 
`override fun onTaskCompleted(list: MutableList<Article>)`, I have to do it using `runOnUiThread` else it throughs exception in `override fun onError(e: Exception)` that `Only the original thread that created a view hierarchy can touch its views.`

Thank you for this important update.
