### ISSUE TITLE
Parsing error when pubDate is Unparseable

### ISSUE THREAD

**Issue by PDACN** [prof18/RSS-Parser#26]
Is possible have pubDate as String and not as Date type?
with this I can parse pubDate with format I want.
https://www.mkb.nl/rss/dossier/1318
onError: java.text.ParseException: Unparseable date: "08/06/2018 - 08:00"

or in case the articleslist with pubDate = null

**Comment by prof18** [comment]
Since all the problems with the format of the date, I think that the solution that you propose is the cleverest. I'll implement it in the next release.

**Comment by prof18** [comment]
I've released a new version that saves the date as String. Please update and use version 2.0.3

**Comment by PDACN** [comment]
now with 2.0.3 work without problem
thanks
