### ISSUE TITLE
cannot correctly parse rss link information

### ISSUE THREAD

**Issue by sk166** [prof18/RSS-Parser#29]
please check this rss feed.
It cannot parse links correctly if there is more than one link in article
www.aif.ru/rss/news.php

**Comment by prof18** [comment]
Hi, 
what do you mean with multiple links? I've checked and tested the link that you have provided and It works. If you post a snippet with the feed that causes the problem then I can test more specifically.

**Comment by prof18** [comment]
I close it for inactivity
