### ISSUE TITLE
Project does not building when android:allowBackup="false" is set in Manifest

### ISSUE THREAD

**Issue by spipau** [prof18/RSS-Parser#3]
The application can no longer be built when the application has `android:allowBackup="false"` because the library has `android:allowBackup="true"` :

```
Error:Execution failed for task ':app:processFreeDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:30:9-36
  	is also present at [com.prof.rssparser:rssparser:1.0] AndroidManifest.xml:12:9-35 value=(true).
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:28:5-166:19 to override.
```

Suggestion: remove the `android:allowBackup="true"` from the lib manifest.

Additional, maybe also remove `android:label="@string/app_name"` and `android:supportsRtl="true"`

**Comment by prof18** [comment]
Thanks for the tip. I'll fix it soon.

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by prof18** [comment]
Hi, 
I've just updated the library with the fix. Again, thanks for the tip!

**Comment by spipau** [comment]
Great! Thanks! 
Please let me know when you also update the lib in JCenter, so I can include your nice work into my project via gradle ;)

**Comment by prof18** [comment]
I've already updated it!

**Comment by spipau** [comment]
Ah, 1.0 --> 1.1 :)
Thanks, works like a charm!

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
