### ISSUE TITLE
Is there a way to stop the background thread?

### ISSUE THREAD

**Issue by javmarina** [prof18/RSS-Parser#30]
Until now, as Parser was just an AsyncTask, I would call parser.cancel(boolean mayInterruptIfRunning). However, this is no longer possible. Is there a way to interrupt or cancel the background processing with the new system?

**Comment by prof18** [comment]
If you are using Kotlin, you can simply cancel the job, like in the sample code:
https://github.com/prof18/RSS-Parser/blob/753d297aa6b792c8da7e472d315cdec54f56abb6/samplekotlin/src/main/java/com/prof/rssparser/sample/kotlin/MainViewModel.kt#L61

Instead, If you are using Java, in the next version the method `cancel()` will be available in the Parser class.

**Comment by prof18** [comment]
Fixed with release 2.0.5
