### ISSUE TITLE
Parse multiple rss url.

### ISSUE THREAD

**Issue by desaivishal11** [prof18/RSS-Parser#4]
How to parse multiple RSS URL. And wait for each to finish.

**Comment by spipau** [comment]
Hi,

I'm not the author of this library, but this is a issue tracker and not a "ask a question" tool... you should put your question on [Stackoverflow](https://stackoverflow.com) ;)
Send me the link and I can then post what I did: I have a list of 5 RSS Links and use recursion to execute them one-by-one.

Best,
Paul

**Comment by prof18** [comment]
Hi,

I'm totally agree with @spipau . If you have some question related to implementation, you can ask on Stackoverflow or on [the blog post on my website dedicated to that library. ](http://www.marcogomiero.com/blog/rss-parser-library/).

The issue tracker has to be used only for reporting bugs
