### ISSUE TITLE
for blogs from blogspot displaying null for the article

### ISSUE THREAD

**Issue by faisalhalim** [prof18/RSS-Parser#42]
when I run with url feed from blogspot with url https://www.halimlab.com/feeds/posts/default?alt=rss article displays **null**

**Comment by prof18** [comment]
That's because the keyword used in the feed are not supported. 

Please refer to the following object for the supported keywords

https://github.com/prof18/RSS-Parser/blob/5eb12ade03b05565312735a992450cbba63be530/rssparser/src/main/java/com/prof/rssparser/utils/RSSKeywords.kt#L20-L36
