### ISSUE TITLE
OkHttpClient setter or constructor

### ISSUE THREAD

**Issue by FriedrichM** [prof18/RSS-Parser#43]
Hi, 
Great library  you've made there. I am using it on my app with minsdk 17, which
makes default tlsv1.2 support a bit of a pain. It would be great, if there was a way to set 
a custom OkHttpClient for the library to be used. 
I would do a pull request but i dont know Kotlin :( 
But i think its not that hard of a feature to implement. 
Just make the constructor take an OkHttpClient instance as an argument or do a setter for the client.
I've done it in java and it wokrs fine .

`

    private OkHttpClient myclient;
    private OnTaskCompleted onComplete;
    public Parser() {
        xmlParser = new XMLParser();
        xmlParser.addObserver(this);
    }
    public Parser(OkHttpClient client) {
        this.myclient = client;
        xmlParser = new XMLParser();
        xmlParser.addObserver(this);
    }
    public interface OnTaskCompleted {
        void onTaskCompleted(ArrayList<com.prof.rssparser.Article> list);

        void onError(Exception exception);
    }
    public void onFinish(OnTaskCompleted onComplete) {
        this.onComplete = onComplete;
    }
    @Override
    protected String doInBackground(String... ulr) {
        Response response = null;
        OkHttpClient client = null;
        if(myclient!=null)
            client=myclient;
        else
            client=new OkHttpClient();
        Request request = new Request.Builder()`

**Comment by prof18** [comment]
Thanks for sharing, it's definitely an improvement to do.

**Comment by prof18** [comment]
Fixed with release 2.0.5
