### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by norrisboat** [prof18/RSS-Parser#5]
Thanks for this awesome library. Was wondering if there's a way to achieve pagination with this library.

**Comment by norrisboat** [comment]
I've figured it out by just adding the page number to the url e.g http://xxx.com/feed?paged=pageNumber and it works. Thanks.

**Comment by prof18** [comment]
Oh, fantastic! Sorry if I didn't reply sooner but I'm really busy these days.

**Comment by norrisboat** [comment]
No problem @prof18 . Sometime the image field is null

**Comment by prof18** [comment]
Probably that's because the site has some item without the image

**Comment by norrisboat** [comment]
It appears with other rss libraries and other times content is null

**Comment by prof18** [comment]
This library takes as main image the first one encountered in the text. If in the text there aren't images the field will be null. Probably the other libraries takes the main image from a dedicated field in the feed

**Comment by norrisboat** [comment]
Ok thanks very much

**Comment by guiltydarkness1313** [comment]
@norrisboat which libraries do you use to get the image of the feed?

**Comment by prof18** [comment]
@guiltydarkness1313 In the sample app I use [Picasso](https://github.com/square/picasso)

**Comment by norrisboat** [comment]
@guiltydarkness1313 I use [Universal Image Loader](https://github.com/nostra13/Android-Universal-Image-Loader)
