### ISSUE TITLE
Conflicting gradle 'compile' line

### ISSUE THREAD

**Issue by cheburakha** [prof18/RSS-Parser#51]
Hey, thanks for your library!

I'm still coding with a Java stack so I've tried to include your gradle variant.
The issue is that gradle has recently deprecated the 'compile' option - so I replaced it with the
```

implementation ("com.prof.rssparser:rssparser:2.0.4") {
    exclude group: 'org.jetbrains', module: 'annotations'
}

```
section - 'exclude' option is because i've already had an
```
implementation 'org.jetbrains:annotations-java5:15.0'
```
line - that issued a ton of a 
`Duplicate class org.intellij.lang.annotations.Flow found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)`
errors, so I bypassed em by staying with already present annotations.

Cheers!

**Comment by prof18** [comment]
Thank you! There was a typo on the Readme. I forgot to change from `compile` to `implementation` back then.
