### ISSUE TITLE
Channel Description

### ISSUE THREAD

**Issue by aaugsten** [prof18/RSS-Parser#55]
"channelDescription" is not set, if "RSSKeywords.RSS_CHANNEL_IMAGE" comes before "RSSKeywords.RSS_ITEM_DESCRIPTION".

Possible fix (didn't check):
In "CoreXMLParser.kt" remove "insideChannel = false" from "RSSKeywords.RSS_CHANNEL_IMAGE" and add it to "eventType == XmlPullParser.END_TAG && xmlPullParser.name.equals("channel", ignoreCase = true)".

Please refer to this rss:
http://joeroganexp.joerogan.libsynpro.com/rss

**Comment by prof18** [comment]
Thanks for reporting, the fix is available on 2.1.1
