### ISSUE TITLE
java.net.ProtocolException: Expected leading [0-9a-fA-F] character but was 0x1f

### ISSUE THREAD

**Issue by lbarrosop** [prof18/RSS-Parser#6]
Hi, testing this url http://www.prensa-latina.cu/index.php?o=vc&id=principal&SEO=canalrss-principal   the library throws this error: 

 W/System.err: java.net.ProtocolException: Expected leading [0-9a-fA-F] character but was 0x1f
09-07 11:24:34.088 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at okhttp3.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:448)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at okhttp3.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:422)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.java:50)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at okio.RealBufferedSource.request(RealBufferedSource.java:71)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at okio.RealBufferedSource.require(RealBufferedSource.java:64)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at okio.GzipSource.consumeHeader(GzipSource.java:114)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at okio.GzipSource.read(GzipSource.java:73)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at okio.Buffer.writeAll(Buffer.java:956)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:92)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at okhttp3.ResponseBody.bytes(ResponseBody.java:83)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at okhttp3.ResponseBody.string(ResponseBody.java:109)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at com.prof.rssparser.Parser.doInBackground(Parser.java:68)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at com.prof.rssparser.Parser.doInBackground(Parser.java:34)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-07 11:24:34.093 18673-20271/cu.entumovil.barrosofeedsnews W/System.err:     at java.lang.Thread.run(Thread.java:818)

Is there any way to fix it?

**Comment by prof18** [comment]
Hi, I'll check it asap

**Comment by lbarrosop** [comment]
Hello, did you get any good results about this problem?

**Comment by prof18** [comment]
Hi, sorry for the very loooong delay. I've tried loading the example application with your feed and everything is working!
