### ISSUE TITLE
Article image in Bing feed

### ISSUE THREAD

**Issue by juanro49** [prof18/RSS-Parser#60]
Hi, can you add support to get image of articles in Bing News feed?
This is a example https://www.bing.com/news/search?q=esparragosa&format=rss

Article image is in <<News:Image>> tag.

Thanks for the support.

**Comment by prof18** [comment]
Sorry that I got back to you earlier, but this feature has been introduced a while back. I just added some tests to check it.

**Comment by juanro49** [comment]
> Sorry that I got back to you earlier, but this feature has been introduced a while back. I just added some tests to check it.

@prof18  Sorry, but I meant the images of the articles, not the RSS. The RSS image is now obtained correctly, but the image of the articles, which was the one that said to add the support, is not obtained.

Example: https://www.bing.com/news/search?q=madrid&format=rss

![imagen](https://user-images.githubusercontent.com/11600804/106369654-8af9e380-6353-11eb-8c18-09a236e29385.png)

![imagen](https://user-images.githubusercontent.com/11600804/106369507-6bae8680-6352-11eb-9ef1-7dbb24d14634.png)

you should add support to the <News:Image> which indicates the article image in the bing RSS.

Thank you for the support!! 😊️
