### ISSUE TITLE
Not parsing urls that end with .rss

### ISSUE THREAD

**Issue by eagskunst** [prof18/RSS-Parser#63]
The parser seems to hang when a link that ends with .rss is send. 
You can try with the following:

- https://www.unilad.co.uk/gaming.rss
- https://www.unilad.co.uk/index.rss

It you're too busy, I can make the change and send a PR but I will like some direction of what I exactly have to change in order to succesfully parse this type of URL 😅

**Comment by prof18** [comment]
I've tried with both the links and it works without any issues!

![Screenshot_1583675002](https://user-images.githubusercontent.com/9467705/76163991-3520b980-614b-11ea-9966-123b0afe965d.png)
