### ISSUE TITLE
Open Link URL

### ISSUE THREAD

**Issue by bhutanict** [prof18/RSS-Parser#64]
To open Link URL like twitter and so on.

**Comment by prof18** [comment]
I don't understand your request. The library only parses rss link. Can you provide a more detailed example of what you want?

**Comment by noloman** [comment]
I guess what @bhutanict wants is the library to also parse the content of the HTML that lives inside the `<link>` section of an `<item>` inside a `<channel>`?

**Comment by bhutanict** [comment]
What I wanted was to open the link section in Android web browser. I have done myself.
