### ISSUE TITLE
after opening a post it shows "null"

### ISSUE THREAD

**Issue by iamnk140** [prof18/RSS-Parser#67]
**Describe the bug**
After opening the fees item it shows "null"

**The link of the RSS Feed**
http://feeds.bbci.co.uk/news/world/rss.xml

![Screenshot_20200412-214134](https://user-images.githubusercontent.com/46350409/79073872-93225d00-7d06-11ea-942d-548fe8febf09.jpg)

**Comment by marabu4a** [comment]
because the descroption of RSS feed is null

**Comment by iamnk140** [comment]
> because the description of RSS feed is null

It is not null, but the library is nit supporting RSS

**Comment by prof18** [comment]
It's because the `content:encoded` tag is null.
