### ISSUE TITLE
Unable to add to my project

### ISSUE THREAD

**Issue by ajurcevic** [prof18/RSS-Parser#7]
Having trouble adding this to my project.

I add the dependency to my app bundle but then attempt a re-sync it gives a big old 👎 
`Error:(88, 13) Failed to resolve: com.prof.rssparser:rssparser:1.1`

Doesn't seem like its on JCenter.

**Comment by prof18** [comment]
Mmm, The project is correctly uploaded. Have you tried again?

**Comment by ajurcevic** [comment]
works now.
user error i guess...

cheers.
