### ISSUE TITLE
XmlPullParserException: Unexpected token

### ISSUE THREAD

**Issue by JJSWART** [prof18/RSS-Parser#75]
**Describe the bug**
When handling the specific url I get this error?
org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ο»Ώ@1:4 in java.io.InputStreamReader@325fadc) 

My method:

```
        parserBuilder.parser?.execute(url)
        parserBuilder.parser?.onFinish(object : OnTaskCompleted{
            override fun onError(e: Exception) {
                e.printStackTrace()
                Looper()
            }

            override fun onTaskCompleted(channel: Channel) {
                channel.articles.let { list.addAll(it) }
                Looper()
            }
        })
```

**The link of the RSS Feed**
http://feeds.wheels24.co.za/articles/Wheels/OffRoad_and_4x4/rss

**Comment by prof18** [comment]
Hi, I've tested the library with the feed you provided and it is working without any kind of error. 

This is the feed that I've used for testing: https://github.com/prof18/RSS-Parser/blob/adacf43fb5/rssparser/src/test/resources/feed-test-unexpected-token.xml

**Comment by TwinklingToon** [comment]
i want to fetch content 

      <media:content url="https://images.news18.com/ibnlive/uploads/2023/07/bse-reuters-16894829603x2.jpg" medium="image" height="800" width="1200"/>


please do update
