### ISSUE TITLE
Class file for kotlin.coroutines.Continuation not found

### ISSUE THREAD

**Issue by IvanMazzoli** [prof18/RSS-Parser#79]
Ciao Marco,
while cleaning up a bit my dependencies (or implementations, how they are now called) and then rebuilding it appeared the following error:

```
parser.parse(rawData, NewsActivity.this);
                      ^
  class file for kotlin.coroutines.Continuation not found
```

Tried to clean and rebuild, invalidate the cache but nothing works.
I'm currently using version 3.1.0

**Comment by IvanMazzoli** [comment]
Turns out that my Gradle/Android Studio has some corrupted files. Tested in another PC with the same settings and versions and it works flawlessly.

Sorry for wasting your time!

PS, don't drop Java support :'(

**Comment by prof18** [comment]
Don’t worry!

**Comment by IvanMazzoli** [comment]
Btw, I've also found out that if your project is in Java adding
`implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:0.22.2"`
to the project dependecies helps!
