### ISSUE TITLE
No image available of some sites and null values on WebView

### ISSUE THREAD

**Issue by guiltydarkness1313** [prof18/RSS-Parser#8]
Hi I was using your library with your example and I noticed that all the pages I put to parse the RSS don't get an image and the webView gets a null value.
Thanks for your work.

**Comment by prof18** [comment]
Mmm, the image can be null because the library takes the first image in the content. So if there isn't any images in the content , the image field will be null.

For the webview honestly I don't know. What is the link that you parse?

**Comment by guiltydarkness1313** [comment]
https://elcomercio.pe/feed i was testing this link a anothers and the webview, i think that only works on android central

**Comment by dzyniek** [comment]
Hi mate,

I tried your code as well - starting my journey with android app and got the same issue as friend above. I think it works only for androidcentral or a provider that uses the same feed code as android central - not loading images is the smallest issue - thats fine - can happen but for me when i tried rss from one blog i read when it parsed the feeds but when clicked on article i got webview and 'null' - so even the article text wasnt downloaded
thanks

**Comment by prof18** [comment]
Hi, this library has been built starting from RSS feed generated from a Wordpress Site. Of course it's compatible with RSS feed generated from other tipe of sites; [Here](https://www.androidauthority.com/feed/) you can find an example of RSS feed.
