### ISSUE TITLE
Parser.Builder() gives error

### ISSUE THREAD

**Issue by japarmar** [prof18/RSS-Parser#80]
Android studio can't find Parser.Builder() it gives error.

**Comment by prof18** [comment]
Are you seeing this kind of error?
<img width="927" alt="Screenshot 2020-12-07 at 08 58 18" src="https://user-images.githubusercontent.com/9467705/101324375-737a0f00-386a-11eb-996c-8e4695fd1b53.png">

**Comment by japarmar** [comment]
yes exactly same

**Comment by prof18** [comment]
Ok, got it. I'm working on a fix, but for the time being, you can fix it by adding the okhttp dependency to your project.
