### ISSUE TITLE
No Image in Bing RSS Articles (image of RSS is OK but not items images)

### ISSUE THREAD

**Issue by juanro49** [prof18/RSS-Parser#86]
I reopened this issue because the previous one #66 was closed by confusion.

> Sorry that I got back to you earlier, but this feature has been introduced a while back. I just added some tests to check it.

@prof18  Sorry, but I meant the images of the articles, not the RSS. The RSS image is now obtained correctly, but the image of the articles, which was the one that said to add the support, is not obtained.

Example: https://www.bing.com/news/search?q=madrid&format=rss

![imagen](https://user-images.githubusercontent.com/11600804/106369654-8af9e380-6353-11eb-8c18-09a236e29385.png)

![imagen](https://user-images.githubusercontent.com/11600804/106369507-6bae8680-6352-11eb-9ef1-7dbb24d14634.png)

you should add support to the <News:Image> which indicates the article image in the bing RSS.

Thank you for the support!! 😊️

_Originally posted by @juanro49 in https://github.com/prof18/RSS-Parser/issues/60#issuecomment-770291323_

**Comment by prof18** [comment]
Hi,
thanks for reporting. I fixed the issue and a new version will be released soon.
