### ISSUE TITLE
Neither channel nor item images are found

### ISSUE THREAD

**Issue by brad-thaler** [prof18/RSS-Parser#87]
**Describe the bug**
Using v3.1.3 of the library (Java), both channel and item images are null, even tho they exist in the RSS feed.

    <channel>
        ...
        <image>
            <url>https://a.espncdn.com/i/espn/teamlogos/lrg/trans/espn_dotcom_black.gif</url>
            <title>www.espn.com - TOP</title>
            <link>https://www.espn.com</link>
            <width>110</width>
            <height>110</height>
        </image>
        ...
        <item>
            ...
            <image>
                <![CDATA[ https://a.espncdn.com/photo/2021/0204/r810514_1296x864_3-2.jpg ]]>
            </image>
            ...
        </item>
        ...
    </channel>

**The link of the RSS Feed**
https://www.espn.com/espn/rss/news

**Comment by prof18** [comment]
Hi,
thanks for reporting. I fixed the issue and a new version will be released soon.
