### ISSUE TITLE
String encoding

### ISSUE THREAD

**Issue by jeffnyauke** [prof18/RSS-Parser#88]
![2021-05-31 (2)](https://user-images.githubusercontent.com/14073448/120124873-0747ea80-c1bf-11eb-9edc-ad0c29435998.png)
The resulting strings are encoded. This should not be the case. Look at the title.

**Comment by prof18** [comment]
Hi,
can you share the link to the feed, so I can check it out?

**Comment by jeffnyauke** [comment]
https://rss.nytimes.com/services/xml/rss/nyt/Health.xml

**Comment by jeffnyauke** [comment]
Any feedback?

**Comment by prof18** [comment]
Sorry for the delay, I'm gonna look into it in the next few days!

**Comment by prof18** [comment]
I've written a test case that covers the issue you reported and it's working.  Unfortunately, the item of the feed you reported is not available anymore and I have used a similar one (the title is `Where the Grass is Greener, Except When It’s ‘Nonfunctional Turf’` wich is similar to `‘On That Edge of Fear’: One Woman’s Struggle With Sickle Cell Pain` that you have reported)

Let me know if is working for you or if you still have the past feed so I can test it out with it.

**Comment by prof18** [comment]
Perfect! I'm glad you solved the issue.
