### ISSUE TITLE
Read <enclosure> tag (not in Article class)

### ISSUE THREAD

**Issue by PepaZapletal** [prof18/RSS-Parser#96]
Hi,

in my RSS Feed is a `<enclosure>` tag. In that tag is URL to image. But I don't see this tag in `Article` class. 

How can I access to the `<enclosure>` tag? What should I change?

**The link of the RSS Feed**
[https://www.cdv.cz/assets/rss.xml](https://www.cdv.cz/assets/rss.xml)

**Comment by prof18** [comment]
Hi!
It will be possible with the next release!
